#! /bin/sh

sxhkd &

if [[ $(hostname) == 'arch-desktop' ]]; then
    xrandr --output DVI-D-0 --off --output HDMI-0 --mode 1920x1080 --pos 3840x472 --rotate normal --output DVI-I-1 --off --output DVI-I-0 --mode 1280x1024 --pos 0x624 --rotate normal --output DP-1 --off --output DP-0 --primary --mode 2560x1440 --pos 1280x0 --rotate normal
    bspc monitor DP-0 -d I II III IV
    bspc monitor HDMI-0 -d V VI VII VIII 
    bspc monitor DVI-I-0 -d IX X
elif [[ $(hostname) == 'arch' ]]; then
    xinput set-prop 11 289 1
    bspc monitor -d I II III IV V VI
else
    bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config border_width         0
bspc config window_gap           12
bscp config top_padding          23
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_radius        10
bspc config presel_feedback_color "#969696"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=o
bspc rule -a Screenkey manage=off

nohup nm-applet >/dev/null 2>&1 &
betterlockscreen -w
nohup bash $HOME/.dotfiles/polybar/launch.sh >/dev/null 2>&1 &
nohup clipit >/dev/null 2>&1 &
nohup compton --unredir-if-possible -C >/dev/null 2>&1 &
nohup mopidy >/dev/null 2>&1 &

bspc config top_padding 23
bspc config right_padding -6
bspc config left_padding -6
bspc config bottom_padding -6

