#! /bin/sh

sxhkd &

if [[ $(hostname) == 'arch-desktop' ]]; then
#    xrandr --output DVI-D-0 --off --output HDMI-0 --mode 1920x1080 --pos 3840x472 --rotate normal --output DVI-I-1 --off --output DVI-I-0 --mode 1280x1024 --pos 0x624 --rotate normal --output DP-1 --off --output DP-0 --primary --mode 2560x1440 --pos 1280x0 --rotate normal
xrandr --output HDMI-0 --mode 1920x1080 --pos 3840x623 --rotate normal --output DP-0 --primary --mode 2560x1440 --pos 1280x0 --rotate normal --output DP-1 --off --output DP-2 --mode 1280x1024 --pos 0x651 --rotate normal --output DP-3 --off --output DP-4 --off --output DP-5 --off

    bspc monitor DP-0 -d I II III IV
    bspc monitor HDMI-0 -d V VI VII VIII
    bspc monitor DP-2 -d IX X
elif [[ $(hostname) == 'arch' ]]; then
    xinput set-prop 11 304 1
    bspc monitor -d I II III IV V VI
elif [[ $(hostname) == 'arch-thinkpad' ]]; then
    bspc monitor -d I II III IV V VI
else
    bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config border_width         0
bspc config window_gap           6
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_radius        10
bspc config presel_feedback_color "#969696"
bspc config focused_border_color '#474645'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=o
bspc rule -a Screenkey manage=off
bspc rule -a Zathura -o state=tiled

picom -Cb --animations
nm-applet >/dev/null 2>&1 &
betterlockscreen -w
bash $HOME/.config/polybar/launch.sh >/dev/null 2>&1 &
clipit >/dev/null 2>&1 &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 >/dev/null 2>&1 &
dunst >/dev/null 2>&1 &

bspc config top_padding 36
bspc config right_padding 0 #-6
bspc config left_padding 0 #-6
bspc config bottom_padding 0 #-6

setxkbmap -layout us
xsetroot -cursor_name left_ptr &
xsetroot -xcf /usr/share/icons/Adwaita/cursors/left_ptr 24

export QT_QPA_PLATFORMTHEME=qt5ct
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

